# Generated by Django 5.0.2 on 2024-02-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lesson_teacher_appendix_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(max_length=125),
        ),
    ]
