# Generated by Django 5.0.2 on 2024-02-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_teacher_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appendix',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
