# Generated by Django 5.0.2 on 2024-02-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appendix_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='video_id',
            new_name='video_embed_url',
        ),
    ]
