# Generated by Django 5.0.2 on 2024-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_contactmessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.TimeField(auto_now_add=True, verbose_name='created at'),
        ),
    ]
