# Generated by Django 5.0.2 on 2024-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_is_admin_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lessons_registered',
            field=models.ManyToManyField(to='base.lesson', verbose_name='Lessons Registered'),
        ),
    ]
