# Generated by Django 5.0.2 on 2024-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_video_id_lesson_video_embed_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appendix',
            old_name='link',
            new_name='linkURL',
        ),
        migrations.AddField(
            model_name='appendix',
            name='linkname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
